### ISSUE TITLE
Add new gapless reciters: Sheikh Qari Yassin & I.Doussery

### ISSUE THREAD

**Issue by nacer80** [quran/quran_android#1392] opened 2020-06-29 18:55 UTC
السلام عليكم ورحمة الله وبركاته 

For warsh version, I hope that we add the famous shouiokh of reweyet warsh: sheikh Qari Yassin Eljzairy and sheikh Ibrahim Doussery.

**Comment by ahmedre** [comment] 2020-06-29 18:57
closed as duplicate of #1391

**Closed by ahmedre** 2020-06-29 18:57 UTC
