### ISSUE TITLE
Document the code

### ISSUE THREAD

**Issue by shahrukhmlk** [quran/quran_android#697] opened 2016-10-31 13:05 UTC
Please document the code so that we can contribute to the code.
جزاك الله على ذلك العمل الجميل

**Comment by ozbek** [comment] 2016-11-01 06:25
That's a very good suggestion. However, that's easier said than done. After all, writing docs is one of the most hated part of any programmer's job :)

To help with the cause, may I suggest you to ask about the parts that are not clear for you? At least, that way, the maintainers will know from where to start documenting the code.

**Comment by hulk9914** [comment] 2016-11-03 06:17
I suggest to start documenting by putting a brief description at the beginning of each class to help other developers understand what is the role of each class.

**Comment by ahmedre** [comment] 2017-01-12 08:33
i am closing this issue for now, but i definitely agree and will start adding more comments insha'Allah

**Closed by ahmedre** 2017-01-12 08:33 UTC
