### ISSUE TITLE
Post on fdroid

### ISSUE THREAD

**Issue by Thewisem** [quran/quran_android#1526] opened 2021-01-06 01:16 UTC
This is an FOSS quran app and I would love it if you could post this on Fdroid. The FOSS platform. It will help in reaching more people and many people will consided your app more

**Comment by ozbek** [comment] 2021-01-06 02:52
Salam!

This looks like a duplicate of #434 and/or #755.

**Comment by Thewisem** [comment] 2021-01-07 16:56
Huh So people DID ask this ok

**Comment by Thewisem** [comment] 2021-01-07 16:56
Well then please do it

**Comment by Thewisem** [comment] 2021-01-07 17:13
Huh! Ok then please do it. It would help us in updating the app
Waalaykummusalam

**Comment by ahmedre** [comment] 2021-03-20 21:36
closing in favor of #755

**Closed by ahmedre** 2021-03-20 21:36 UTC
