### ISSUE TITLE
Quran (Arabic) text in translation/tafseer has errors

### ISSUE THREAD

**Issue by mbarbar** [quran/quran_android#926] opened 2018-01-09 13:31 UTC
Assalamu alaykum,

Noticed at a glance that some of the Quran is incorrect or incomplete in the translation/tafseer section of surat Al-Alaq. The screenshots explain it all. 

**The second screenshot is most important** where a word is changed completely. Otherwise, hamzat wasl, the little meem, and the madd symbol are all missing. I also noticed in ayat 9, 11, and 13, the hamza is sitting on an alif.

![al-alaq_error_1](https://user-images.githubusercontent.com/12083002/34723132-8cc7f48a-f59d-11e7-8888-b59c0a4a6773.png)
![al-alaq_error_2](https://user-images.githubusercontent.com/12083002/34723133-8d00fa6e-f59d-11e7-9cae-e1a4a08cd5b1.png)
![al-alaq_error_3](https://user-images.githubusercontent.com/12083002/34723134-8d2c95fc-f59d-11e7-9943-0f10765749b8.png)

I'm not sure if there are other errors, or if other suwar have the same issues, but it might be worth an look into the source of the text.

**Comment by ahmedre** [comment] 2018-01-11 07:09
wa3laikum alsalam,
this isn't an error, but we're looking to improve it nevertheless - let me explain. today, if you were to write the word in written Arabic (i.e. in a letter or newspaper or essay), you'd write it using an "imlaei" style. when you write in the Quran, the same word is written differently, in an "uthmani" style. Quran text should ideally always be Uthmani. consequently, it's not an error, but it's not ideal, and so we want to fix it to match the page text as much as possible.

we're thinking about a few things for this insha'Allah.
walsalam 3alaikum.

**Comment by Ahmed9914** [comment] 2018-01-11 07:58
Possible duplicate of issue #721

**Comment by mbarbar** [comment] 2018-01-11 08:58
Jazak Allahu khaira for taking a look.

I suspected such for all but the "رءاه" and I just learnt this:
>If the letter following the hamza is an alif itself: (as in آكل ākul) alif maddah will occur.

Thanks for taking the time to explain. :)

**Closed** 2018-01-11 08:58 UTC
