### ISSUE TITLE
Arabic search engine is not working correctly 

### ISSUE THREAD

**Issue by 3dola** [quran/quran_android#960] opened 2018-06-17 04:41 UTC
1) As an example, please look for the word tombs in Arabic (قبور) then you should get the error msg, "no results found for...قبور" 
2) Searching the Quran script in Arabic brings Quran results mixed with interpretation (tafseer) which makes the experience more difficult and less enjoyable

The search engine accuracy is a must have! 

Thank you for the time and efforts put into this app.

**Comment by asyazwan** [comment] 2018-06-17 12:39
For your first point it’s a known limitation:
#453

**Comment by 3dola** [comment] 2018-06-18 03:17
This alone makes the app incompetent in its league. Primarily because it gives the average user a false impression about the results. 

In this case, maybe the search engine needs to be replaced/rewritten entirely.

**Comment by ahmedre** [comment] 2018-06-18 08:04
yes, absolutely - search is completely unacceptable today.

i intend on rewriting it in sha' Allah. part of it is our hands are slightly tied in the sense that things like stemming, etc don't work in the versions of SQLite that are on Android - but even for those, we have options of what we can do and improve both offline search (in addition to deciding to use online search when the connection is good).

**Comment by Ahmed9914** [comment] 2019-04-23 09:54
possible duplicate of #453

**Comment by ahmedre** [comment] 2019-04-28 22:29
closing because fixed.

**Closed by ahmedre** 2019-04-28 22:29 UTC
