### ISSUE TITLE
Change speed for audio player

### ISSUE THREAD

**Issue by sbou88** [quran/quran_android#1338] opened 2020-05-07 19:41 UTC
Salam a3laykoum, 

It can be useful to reduce or increase speed of audio. 

Saha ftourkoum, 
Saïd

**Comment by ozbek** [comment] 2020-05-11 05:24
Wa 3alaikum salam,

Possible duplicate of #408.

**Comment by ahmedre** [comment] 2020-05-11 16:14
wa3laikum alsalam,
jazakAllah khairan - closing as duplicate.
walsalam 3alaikum.

**Closed by ahmedre** 2020-05-11 16:14 UTC
