### ISSUE TITLE
Feature Request regarding audio playback upgrade

### ISSUE THREAD

**Issue by Abdullah076** [quran/quran_android#853] opened 2017-04-17 19:16 UTC
1. Ability to control recitation speed, which may benefit many people to memorize in sha Allah.
2. Option to set time of Interval between each verses (half of ayah duration, 10/ 30/ 60 seconds etc.) (available in http://www.recitequran.com/settings/repeat )
3. Option to sync between any Arabic recitation & translation audios in other languages, so that any verse can be heard with its recitation & translation (Available in ayat app)
4. Improving changing audio directory to External SD card or Internal Memory

**Comment by ozbek** [comment] 2017-04-18 08:15
> Improving changing audio directory to External SD card or Internal Memory

Are you interested in only moving audio files? Otherwise, there is an option for that in `Settings -> Advanced Options -> Quran data directory`.

**Comment by ahmedre** [comment] 2017-04-20 07:56
many people asked for 1 before but i prefer not to do it since it could easily turn into something disrespectful (audio sounds funny when it is either too fast or too slow, and while it's cool with our own voice, i feel like we should avoid this with the Quran).

for point 3, you mean the word highlights in translation that's playing in Arabic or do you mean something like the Ibrahim Walk English Audio we have in the app?

**Comment by Abdullah076** [comment] 2017-04-20 08:37
no for 3; i meant that for example: 
If the sync is turned on;
If Surah fatiha 1:1 is played, then translation (Ibrahim Walk English/ or other Audio translations) will be played automatically after Arabic recitation. Then arabic of 1:2 will be played, and again translation will be played after that.

Basically mixing the Arabic recitation & Audio translations.
if sync is turned off; then only selected audio will play.

about 1 & 4; understood.

**Comment by ahmedre** [comment] 2017-04-20 08:40
ah then yes, we definitely want to do that insha'Allah

**Comment by Abdullah076** [comment] 2017-04-20 08:44
jazakumullahu khairan

**Comment by ozbek** [comment] 2017-06-22 01:32
1. Possible duplicate of #408.

**Comment by ozbek** [comment] 2017-06-22 01:34
@Abdullah076, may I suggest you to move number 3 to a separate issue (give it a more descriptive title on the way) and close this one please? Title "Feature Request..." is too ambiguous.

**Closed** 2017-09-08 19:22 UTC
