### ISSUE TITLE
adapt application for Android TV

### ISSUE THREAD

**Issue by sbou88** [quran/quran_android#1339] opened 2020-05-07 19:44 UTC
Salam A3laykoum, 

What about android TV ?

Saïd.

**Comment by ozbek** [comment] 2020-05-11 05:21
Wa 3laykum salam,

Possible duplicate of #945.

**Comment by ahmedre** [comment] 2020-05-11 16:12
wa3laikum alsalam,
jazakAllah khairan - closing as duplicate, we can discuss in the other issue in sha' Allah.
walsalam 3alaikum.

**Closed by ahmedre** 2020-05-11 16:12 UTC
