### ISSUE TITLE
Translation sometimes won't save its place

### ISSUE THREAD

**Issue by ahmedre** [quran/quran_android#1533] opened 2021-01-08 20:23 UTC
Someone sent this bug and I was able to repro -

1. add an ayah bookmark for the first ayah in the page.
2. go to home screen and then to bookmarks, and tap that bookmark
3. go to translation mode and scroll to the very bottom
4. press home to go to the launcher
5. tap the Quran icon again

expected: you stay at the same place
actual: you end up scrolling to the bookmarked ayah

i found that if you do this without a bookmark, the restoration is fine.

**Comment by ahmedre** [comment] 2021-01-08 20:49
brother says it also happens without a bookmark and sent this video - but i can't repro this case, only the one above.

https://user-images.githubusercontent.com/47771/104062753-71fa8880-5214-11eb-9874-549522f14188.mp4

**Comment by MustafaI** [comment] 2021-01-12 04:19
Assalamu alaikum,
I've been looking through the codebase as I'd like to re-use parts of this project with another open source project. I thought it'd be a good idea to work on some bugs so I can get a better understanding of the codebase. 

With regards to this bug I think the video the brother sent may be demonstrating a different issue, where the expanded tafsir is truncated when the activity is restarted after being stopped (going from app -> home -> app). Would this also be an issue? I can reproduce this as well as the issue you mentioned above. 

Jazakallah khair

**Comment by alimsyed** [comment] 2021-05-22 13:59
@MustafaI brother, were you able to work on this? if not please let me know and I could start working on this.
Salam Aliekum

**Comment by MustafaI** [comment] 2021-05-22 17:59
@alimsyed Waalaykum assalam. I don't recall making much progress on this and unfortunately I won't be able to work on it for a while. Feel free to start work on it.

**Comment by mostafazakaria** [comment] 2024-05-06 00:11
Al salamu Alaikum,

Is this issue still valid? I am asking because last update was 3 years ago, so before starting it I wanted to make sure it is not fixed already or if anyone else is working on it.

 I tried to reproduce the issue. It doesn't happen when I open the translation screen, but it happens when I do the same scenario while the translation bottomsheet dialog is opened while have the Surah and translation together open.

**Comment by ahmedre** [comment] 2024-05-06 19:26
wa3laikum alsalam,
someone recently complained about it, but as you said, in the bottom sheet dialog, not the full screen version. a PR would be welcome!
jazakumAllah khairan.

**Comment by mostafazakaria** [comment] 2024-05-07 23:32
I have checked the issue and it doesn't happen on latest main. It was fixed in this [PR](https://github.com/quran/quran_android/pull/2643) I can confirm that it is fixed as I tested it before and after the PR. So I think this issue can be marked as resolved.

**Closed** 2024-05-08 07:50 UTC
Labels: PRs Welcome
