### ISSUE TITLE
F-Droid Publishing

### ISSUE THREAD

**Issue by mufid** [quran/quran_android#659] opened 2016-06-10 22:15 UTC
I think it would be nice if Quran Android also ported into [F-Droid]. For some reason, we can't open/register Play Store, but we can access F-Droid.

[F-Droid]: https://f-droid.org/

**Comment by ozbek** [comment] 2016-06-11 04:03
Possible duplicate of https://github.com/quran/quran_android/issues/434

**Comment by ahmedre** [comment] 2016-07-04 02:18
closing as duplicate of #434

**Closed by ahmedre** 2016-07-04 02:18 UTC
