### ISSUE TITLE
Playbacj speed

### ISSUE THREAD

**Issue by rishadnm** [quran/quran_android#898] opened 2017-06-21 21:02 UTC
Hello people. First of all congrats to all efforts behind dis app. What i want to know is dat, is der any option to adjust playback speed of audio? I want to hear ayats faster than what its available nw. Or is there any plan to include dat feature in near future? Thnks in advance. Assalaamualaiku.

**Comment by ozbek** [comment] 2017-06-22 01:35
Possible duplicate of #408.

**Closed** 2017-06-22 07:15 UTC
