### ISSUE TITLE
[FEATURE] Ayah highlight change animation

### ISSUE THREAD

**Issue by murtraja** [quran/quran_android#1187] opened 2019-05-23 23:51 UTC
Salaam,

Currently, whenever user selects an Ayah, it gets highlighted immediately and the previous highlight disappears instantly. What needs to be done (high level, brief) in order for the previous highlight to animate, slide to the new spot, and highlight the new Ayah instead of abruptly appearing and disappearing?

The new highlight should essentially "float" from the previous position to the new position. Although, this feature doesn't provide any value functionally, but it does look easy on the eyes. 

Any ideas? How difficult is it? Do we have to take help from a 3rd party library? Are there any performance consideration?

**Comment by ahmedre** [comment] 2019-05-24 11:25
wa3laikum alsalam,
this is an interesting question - the problem is that the ranges and shapes aren't exactly the same, which would make it tricky - also that we're drawing them as multiple rectangles instead of a single shape.

don't have any ideas at the moment - will think about it though and update if i think of anything.
jazakAllah khairan,
walsalam 3alaikum.

**Comment by murtraja** [comment] 2020-04-04 07:06
![highlight_float](https://user-images.githubusercontent.com/7806954/78420532-9b76fa00-766d-11ea-8bdc-feb326d9485c.gif)

Try it here http://infallible-austin-c2e5e6.netlify.com/ (expires in 24 hours)

I have implemented a basic floating highlighter using Javascript to understand the concept.
This DroidCon talk https://www.youtube.com/watch?v=JhryKMOM6GI helped me a lot.

The idea is to make a "compatible" bounding box for every ayah consisting of one `moveTo` command and 8 other `lineTo` commands

In order to interpolate between ayats `a` to `b` calculate the intermediate bounding box by interpolating the arguments of the commands mentioned.

So for instance, for ayat `a` `moveTo` command has arguments `xa` and `ya`, and for ayat `b` the arguments are `ya` and `yb`, then in order to get the `moveTo` for halfway point, we simply have to take the average `moveTo((xa+xb)/2, (ya+yb)/2)`

And this has to be repeated for all the other commands as well and for all the time steps.

![bitmap](https://user-images.githubusercontent.com/7806954/78420816-56a09280-7670-11ea-98ef-d5888090b859.png)
Here, 1 represents the 1st command `moveTo`
and the rest are `lineTo` commands from `i-1` to `i` where `i` ranges from 2 to 8
(the last line from 8 to 1 can be easily done by `closePath`)

Now, coming to the question of interest.
@ahmedre Would you like to have this feature implemented?

**Comment by ahmedre** [comment] 2020-04-04 09:12
wa3laikum alsalam,
neat masha'Allah! sure, wouldn't mind having this (during audio playback especially - not sure if we'd want it on on any ayah jump (though maybe we can just say more generically if the ayah is one before or one after this one, animate, otherwise don't).
walsalam 3alaikum.

**Comment by murtraja** [comment] 2020-04-07 11:00
Update:
https://www.youtube.com/playlist?list=PLyxuW-W0DyhokDZLNHkaYVBy7CSezN7k-
Have uploaded 3 videos demonstrating floating highlights for Page 5, 593, 594.
(Have used youtube because github didn't allow me to upload videos)

> the problem is that the ranges and shapes aren't exactly the same, which would make it tricky - also that we're drawing them as multiple rectangles instead of a single shape.

I should have paid more heed to your words @ahmedre. It was only after I started integrating this in our code base did I notice this.

Change of plans.
At first my initial idea was to have a bounding box for every ayah - a single shape, that will be created in such a way that it will remain compatible with all possible bounding boxes of any ayahs.

This idea came to a screeching halt as soon as I encountered this:
![image](https://user-images.githubusercontent.com/7806954/78658436-cbc9cd00-78e7-11ea-8c1d-1776be6337b7.png)

Notice here that the shapes are disjoint and there are two of them. So I couldn't possibly make a single bounding box for every ayah.

Plan B:
Since every ayah has one or more AyahBounds. Every AyahBounds is a rectangle. So instead of morphing a single bounding box for an ayah into another bounding box for the next ayah, now the problem is to morph `x` AyahBounds for Ayah `a` into `y` AyahBounds for Ayah `b` such that `x` and `y` are integers ranging from 1 (single line ayahs) to 3 or 4 (multiple line ayahs)

![float_highlight](https://user-images.githubusercontent.com/7806954/78661734-e94d6580-78ec-11ea-8ea5-12cd13eb4056.png)

As can be seen from the figure above, for ayat 16, we have 3 overlapping highlights above each other which although vanish after the animation is over, but it is a slight inconvenience. Do take a look at the videos if I am not making sense

**Comment by ahmedre** [comment] 2020-04-07 16:00
i think your idea makes sense but maybe with a slight tweak - so say we're going from:

1 box => 1 box (this case is straight forward)
1 box => 2 boxes (box 1 translates to ayah 2 box 1, and then fade in ayah 2 box 2)
2 boxes => 2 boxes (ayah 1 box 1 translates to ayah 2 box 1 while ayah 1 box 2 translates to ayah 2 box 2).
2 boxes => 3 boxes (same as above and the third one just fades in).
3 boxes => 2 boxes (same as above and third one is just gone).

**Comment by murtraja** [comment] 2020-04-09 16:20
Salaam,

Update:
Please refer to this playlist for the animations https://www.youtube.com/playlist?list=PLyxuW-W0DyhoEDllBVqNmktDrE8fzuppg

Just for the sake of clarity, let's define `x <-> y` as the animation that morphs `x` AyahBounds to `y` AyahBounds and vice versa.
Clearly, we have 6 cases here
1. 1 <-> 1
2. 2 <-> 2
3. 3 <-> 3
4. 1 <-> 2
5. 1 <-> 3
6. 2 <-> 3

@ahmedre, it is fair to say that for **cases 1, 2 and 3**, there is no problem and the morphing works great.

I got another idea for **cases 4 and 5**.
Let's consider `1 -> 3`. We can divide the single AyahBounds `x` into 3 parts, split equally, vertically. Each of those splits maps to the corresponding AyahBounds for `y`. 
And  similarly, for `3 -> 1`, each of the three AyahBounds will "construct" the single AyahBounds piece by piece (3 pieces in this case)
Please refer the video titled _oneToThreeToOne_, where `1 <-> 3` case is shown

Now for the last **case 6**
I have followed two approaches here.
# Approach 1 - Fade
As mentioned by you in the previous comment, let the "extra" box get faded out/in. Please refer to the video titled _twoToThree fade_

# Approach 2 - Division
The idea for this is derived from `1 <-> 2,3` approach as discussed previously. 
So consider `2 -> 3`. Instead of fading in/out the "extra" AyahBounds, we will instead, break up the 2nd AyahBounds of `x` into two parts, such that it becomes compatible with `y`. Now both `x` and `y` have 3 AyahBounds each and morphing will work just fine.
Similarly for the `3 -> 2` case, the last two AyahBounds of `x` will construct the last AyahBounds of `y`. 
Please refer the video titles _twoToThree division_

I like the division approach better, because
1. It is one single clean algorithm
```
1. x, y = (x<y? x : y), (y>x: x : y) // x = min, y = max
1. diff = y.AyahBounds.length - x.AyahBounds.length
2. split x.AyahBounds[-1] into (diff + 1) parts
```
2. The fade looks artificial

@ahmedre, I would love to hear your thoughts on this

**Comment by ahmedre** [comment] 2020-04-09 17:48
wa3laikum alsalam,
i agree with you about division - yeah the fade looks like it's out of nowhere and doesn't actually look that good - i think the other benefit of the division approach is that is what you're using in general for the other base cases.

may Allah reward you for all this great work, jazakAllah khairan!
walsalam 3alaikum.

**Comment by ahmedre** [comment] 2020-09-18 23:24
closing since @murtraja did this in #1313 - jazakumAllah khairan brother!

**Closed by ahmedre** 2020-09-18 23:24 UTC
