### ISSUE TITLE
English translation typo mistakes 

### ISSUE THREAD

**Issue by Somaiagabr** [quran/quran_android#329] opened 2013-08-02 21:34 UTC
sura 17 verse 61. english translation has an error it says 'angles' it should be ' angels'
sahih international

**Comment by ATouhou** [comment] 2015-06-05 10:58
They got their translations from "http://tanzil.net/"   
I have contacted them now regarding this

If any response, I will let you know in here. Else maybe the creator should manually change the .db file they exported from them, after they verify it is indeed an error.

**Comment by ahmedre** [comment] 2017-01-30 05:38
Yusuf Ali - 78:40 - "mere" instead of "metre"

**Comment by ahmedre** [comment] 2017-01-30 07:58
3:112 abdul haleem is not complete

**Comment by ahmedre** [comment] 2017-02-04 00:25
4:145 - Muhsin Khan
"vVerily, the hyprocrites will be in the lowest depths (grade) of the Fire; no helper will you find for them." - no reason for that v at the start.

**Comment by ahmedre** [comment] 2017-02-04 00:26
Yusuf Ali - 51:47 it should say 'space', not 'pace'

**Comment by ahmedre** [comment] 2017-02-04 00:26
in surah 3, verse 131:
Shouldn't it say "prepared" instead of "repaired".

**Comment by ahmedre** [comment] 2017-02-04 00:27
muhsin khan - 3:117 - against misspelled

**Comment by ahmedre** [comment] 2017-02-04 00:27
English translation of Muhsin Khan & Taqiuddin Hilali in 11:18 there is a typo.

18. "And who does more wrong than he who invents a lie against Allah. Such wi, l be ..."

It should be corrected to

18. "And who does more wrong than he who invents a lie against Allah. Such will be..."

Barak Allah feekum. May Allah accept your efforts.

**Comment by ahmedre** [comment] 2017-02-04 00:27
Mufti Taqi Uthmani

another one - sura 27 (Naml) ayah 62 -
"... Or the One who responds to a helpless person when **He** prays to Him and removes distress"

the **He** shouldn't have a capital H.

**Comment by ahmedre** [comment] 2017-02-04 00:27
Mufti Taqi Uthmani

sura 30 ayah 24 -
"And it is among His signs that He shows you the **lightening** which causes fear and hope, and that He sends down water from the sky, then He revives the earth with it after its death. Surely in this there are signs for a people who understand"

lightening is misspelled, should be lightning.

**Comment by ahmedre** [comment] 2017-02-04 00:27
Mufti Taqi Uthmani

sura 30 ayah 48 -
"Allah is the One who sends the winds, so they stir up a cloud, then He spreads it in the sky however **he** wills, and makes it (split) into pieces. Then you see the rain coming out from its midst. So, once He makes it reach those whom He wills from His slaves, they start rejoicing"

h should be capital here

**Comment by ahmedre** [comment] 2017-02-04 00:27
Mufti Taqi Uthmani -
sura 56:72 has a "5" in it that shouldn't be there.

**Comment by ahmedre** [comment] 2017-02-04 00:28
Mufti Taqi Uthmani - 39;44 is not complete.

**Comment by ahmedre** [comment] 2017-02-04 00:28
Yusuf Ali translation of 11:18. Lie is replaced with life.

**Comment by ahmedre** [comment] 2017-02-04 00:28
check Abdul Haleem 2:93

**Comment by ahmedre** [comment] 2017-02-04 00:28
check Abdul Haleem 2:20

**Comment by ahmedre** [comment] 2017-02-04 00:28
> Another notification concerning the: "Saheeh International translation", in Surah Al-Waqi'ah:[56:85] it's written on my: Quran for Android Application: "And Our Angels" while It seems that "Saheeh International translation" actually says: "And We [i.e., Our angels]", which seems more logical if we translate from Arabic, but the meaning effectively may be the Angels, from the Tafsirs. Can you confirm this please ?

**Comment by ahmedre** [comment] 2017-02-04 00:28
Yusuf Ali - 10:85 - "our" instead of "out"

**Comment by ahmedre** [comment] 2017-02-04 00:28
Abdul Haleem - 88:17 - translates ibl as rain clouds - all other English translations use camel

**Comment by ahmedre** [comment] 2017-02-04 00:28
Sahih Intl - 42:9 - "him" should be "Him"

**Comment by ahmedre** [comment] 2017-02-20 02:58
Yusuf Ali - 3:3 and 3:4 are joined

**Comment by ahmedre** [comment] 2017-03-13 02:02
Muhsin Khan - Sura Munafiqeen verse 6

"It is equal to them whether you (Muhammad SAW) ask forgiveness or ask not forgiveness for them. Verily, Allah guides not the people who are the Fasiqin (rebellious, disobedient to Allah)."

The phrase "Allah will never forgive them" was omitted.

**Comment by ahmedre** [comment] 2018-11-30 20:31
> There is a mistake in how the translation for 23 carries on into ayah 24 in surah 71.

**Comment by ahmedre** [comment] 2018-11-30 20:44
mufti taqi usmani - ma'idah ayah 82 has a random 46 in it

**Comment by ahmedre** [comment] 2018-12-01 10:35
yusuf ali 51:47 - pace should be space

**Comment by ahmedre** [comment] 2018-12-01 12:15
36:15 and 36:16 abdulhaleem switched?

**Comment by ahmedre** [comment] 2018-12-01 12:44
yusuf ali 11:18

**Comment by ahmedre** [comment] 2018-12-01 12:52
sura munafiqoon ayah 6 - muhsin khan - missing translation for "لَنْ يَغْفِرَ اللَّهُ لَهُمْ"

**Comment by ahmedre** [comment] 2018-12-01 14:52
abdulhaleem 2:20

**Comment by ahmedre** [comment] 2018-12-01 19:19
sahih international - sura isra' ayah 91

**Comment by ahmedre** [comment] 2018-12-01 19:43
khan-hilali - 2:250

**Comment by ahmedre** [comment] 2018-12-01 20:08
2:275 is incomplete - not sure which translator

**Comment by ahmedre** [comment] 2018-12-01 20:17
sura maryam ayah 48 - looser should loser in Mufti Taqi translation

**Comment by ahmedre** [comment] 2018-12-01 20:38
check muhsin khan - 8:44
and also 10:12

**Comment by ahmedre** [comment] 2018-12-07 22:51
mufti taqi - 48:29 - typo

**Comment by ahmedre** [comment] 2018-12-28 21:18
88:17 abdulhaleem says rain clouds - all other english translations say camels

**Comment by naveed-ahmad** [comment] 2019-02-03 20:11
Comments with 👍 are fixed

**Comment by ahmedre** [comment] 2019-03-01 14:58
mufti taqi uthmani - 16:41 has a "6" randomly in it.

**Comment by ahmedre** [comment] 2020-03-23 15:44
yusuf ali - 64:18 is missing "alghayb" - ours said:

> Knower of what is open, Exalted in Might, Full of Wisdom.

Kindle version says:

> Knower of what is hidden and what is open, Exalted in Might, Full of Wisdom.

**Comment by ahmedre** [comment] 2020-03-23 15:49
sahih international - 3:59 -

> Indeed, the example of Jesus to Allah is like that of Adam. He created Him from dust; then He said to him, "Be," and he was.

should be "He created him from dust" (lowercase h). verified in pdf version.

**Comment by ahmedre** [comment] 2020-03-23 15:55
yusuf ali - 5:94 -

was:

> O ye who believe! Allah doth but make a trial of you in a little matter of game well within reach of game well within reach of your hands and your lances, that He may test who feareth him unseen: any who transgress thereafter, will have a grievous penalty.

which is wrong (duplicate "game well within reach of"). Kindle edition says:

> O ye who believe! Allah doth but make a trial of you in a little matter of game well within reach of your hands and your lances, that He may test who feareth Him unseen: any who transgress thereafter, will have a grievous penalty.

**Comment by ahmedre** [comment] 2020-03-23 16:09
59:7 is missing the translation of "wal masakeen" in Sahih International.

he's right - checked the pdf but it also doesn't have it, but [noor international](https://noorinternational.net/en/Translation/AyatTranslations?SoraNum=59&LanguageID=2), the sahih international rebrand, does have it, the difference being "and the needy."

instead of:

> and orphans and the [stranded] traveler

replacing with:

> and orphans and the needy and the [stranded] traveler

**Comment by ahmedre** [comment] 2020-03-23 16:27
sahih international - 18:65 - "we had given mercy from us" the "we" and "us" should be capitalized for royal we/us. confirmed in both pdf and in Noor International.

before:

> And they found a servant from among Our servants to whom we had given mercy from us and had taught him from Us a [certain] knowledge.

after (replacing with newest version):

> And they found a servant from among Our servants [i.e., al-Khidhr] to whom We had given mercy from Us and had taught him from Us a [certain] knowledge.

**Comment by ahmedre** [comment] 2020-03-23 16:32
Yusuf Ali - 114:3 - "god" and "judge" should be capitalized.

old one:

> The god (or judge) of Mankind,-

the kindle version looks like:

> The God (or Judge) of Mankind

**Comment by ahmedre** [comment] 2020-03-23 16:46
Pickthall - 2:96 

> would be no means remove him 

should be:

> would by no means remove him 

was: 

> And thou wilt find them greediest of mankind for life and (greedier) than the idolaters. (Each) one of them would like to be allowed to live a thousand years. And to live (a thousand years) would be no means remove him from the doom. Allah is Seer of what they do.

should be:

> And thou wilt find them greediest of mankind for life and (greedier) than the idolaters. (Each) one of them would like to be allowed to live a thousand years. And to live (a thousand years) would by no means remove him from the doom. Allah is Seer of what they do.

**Comment by ahmedre** [comment] 2020-03-23 18:18
all of these changes now deployed.

**Closed by ahmedre** 2020-03-23 18:18 UTC
Labels: Data
