### ISSUE TITLE
upload it to F-droid

### ISSUE THREAD

**Issue by alezzacreative** [quran/quran_android#1430] opened 2020-09-06 14:59 UTC
hi because of nature of your app as an open source project i encourage you to make it available on the F-droid app store were only open source apps that respect the privacy of the users are
there is a lack of arabic/ islamic apps there
may Allah protect you
the official link : https://f-droid.org/en/
the submission process : https://gitlab.com/fdroid/rfp/

**Comment by benomaire** [comment] 2020-09-06 19:29
Possible duplicate of #755.

Meanwhile, the latest apk is available [here](https://github.com/quran/quran_android/releases) (as an alternative to Google Play).

**Comment by ahmedre** [comment] 2020-09-07 22:25
closing for now - we can resume on the other one in sha' Allah.

**Closed by ahmedre** 2020-09-07 22:25 UTC
