### ISSUE TITLE
Suggestion: add login account 

### ISSUE THREAD

**Issue by nacer80** [quran/quran_android#1446] opened 2020-09-27 04:19 UTC
السلام عليكم ورحمة الله وبركاته 
This suggestion from play store:
![SmartSelect_20200927-071235_Google Play Store](https://user-images.githubusercontent.com/60948528/94355963-b57c1d00-0091-11eb-9e1e-c4c3125e650a.jpg)

**Comment by Riz-waan** [comment] 2020-09-27 18:19
I also think this would be a good idea.

**Comment by benomaire** [comment] 2020-09-30 03:59
Possible duplicate of #342.

For now, I suggest you try using [syncthing](https://f-droid.org/en/packages/com.nutomic.syncthingandroid/) to link `quran_android` folder, this should sync audio, pages, tafsir, translations, but not sure about bookmarks.
I think Syncthing can work on a local network with no Internet as well, and you can add as many devices as you want.

**Comment by Riz-waan** [comment] 2020-10-02 15:39
Can we close this as a duplicate of #342?

I think the original comment used for this post doesn't suggest any other features to the benefit of having accounts other than synchronization so that commenter would be satisfied with a possible solution of #342.

**Closed** 2020-10-02 16:12 UTC

**Comment by benomaire** [comment] 2020-10-02 19:46
This is related:
2020-09-28

> التطبيق رائع جداً. اتمني من المشرفين ان يضعوا خاصيه اضافه حساب حتي استطيع الرجوع الي الصفحه الاخيره التي قرأتها من هاتف آخر وشكراً علي هذا المجهود الرائع.

Specifically, the user needs the last opened page to synchronize.
