### ISSUE TITLE
gapless Audio

### ISSUE THREAD

**Issue by Eng-Fouad** [quran/quran_android#283] opened 2013-04-10 03:29 UTC
Salam Alaikum,

The app is just impressive, may Allah bless you. I was just wondering why don't make all "التلاوات"  to be gapless? Here is one way I am thinking of you can use to implement such feature:
- When "التلاوة" starts, let the background threads to download the next 3 Ayahs.
- When "التلاوة" reaches 3rd ayah for example, the background threads is permitted to download until Ayah 6. and so on.
- You could maintain a queue of Ayah instances, and let the audio manager to pick-up ayahs from that queue. It's simple producer/consumer operation.

I am a Java developer and I can help in this part. Here is my twitter account: @EngineerFouad

Best Regards~

**Comment by ozbek** [comment] 2016-12-13 05:00
Possible duplicate of #231

**Comment by vipafattal** [comment] 2019-07-10 11:07
Salam Alaikum,
I'm impressed by the work that has been done on the app.
I just want to suggest to use Exoplayer in order to get gapless audio it's really an advanced audio framework, I built Quran app inspired by Quran Android that uses Exoplayer to play multiple Ayat. The gape's almost not noticeable in recitation. I'll put a link to test the app, just click on Aya number in the app and press play button.
https://drive.google.com/file/d/1auO-B9aMJlSWd846CylRg9G-ciRnO1u0/view?usp=sharing

I can give the link to the app repository on GitHub if liked the result. 

Thanks for your efforts.

**Comment by ozbek** [comment] 2019-07-11 02:15
Wa alaikum assalam @vipafattal.

Sounds like an awesome upgrade. Tested with "Maher Al Muaiqly", gaps are handled more graciously.

Please send PR.

**Comment by ahmedre** [comment] 2019-07-12 11:41
wa3laikum alsalam,
masha'Allah this is awesome - if you have time to work on a PR, please feel free, otherwise in sha' Allah will try to do this.
walsalam 3alaikum.

**Comment by vipafattal** [comment] 2019-08-18 09:33
Gald you liked it! 
I'm really sorry, but currently, I don't have time to manage to create PR.
Anyway, I have decided to make Musahf open source here is a link to the repository:
[Musahf](https://github.com/vipafattal/Mushaf)
See how I managed to create a media source for every reciter link for streaming play on offline from file play [MediaSourceBuilder.kt](https://github.com/vipafattal/Mushaf/blob/master/app/src/main/java/co/jp/smagroup/musahaf/framework/commen/MediaSourceBuilder.kt) then I'm passing the created media source in [ReciterPlayer.kt](https://github.com/vipafattal/Mushaf/blob/master/app/src/main/java/co/jp/smagroup/musahaf/ui/quran/read/reciter/ReciterPlayer.kt) see ('onDownloadingCompleted' function)  to  [ReadQuranActivity.kt](https://github.com/vipafattal/Mushaf/blob/master/app/src/main/java/co/jp/smagroup/musahaf/ui/quran/read/ReadQuranActivity.kt).

Helpful links to Exoplayer:
[Google codelab](https://codelabs.developers.google.com/codelabs/exoplayer-intro/)
[Google Exolpayer Pub on medium](https://medium.com/google-exoplayer)

**Comment by ahmedre** [comment] 2020-03-26 18:29
today, all except 5 qaris are gapless. likely makes more sense to gapless those qaris instead at this point and remove gapped support completely.

i also have a branch that switches to exoplayer (as of the end of December 2019), though I didn’t plug any special transitioning logic for gapped audio into it. can consider pushing that as the primary player in the future in sha’ Allah.

**Closed by ahmedre** 2020-03-26 18:29 UTC
Labels: Minor, Suggestions
