### ISSUE TITLE
Improving search

### ISSUE THREAD

**Issue by asyazwan** [quran/quran_android#453] opened 2014-10-01 05:13 UTC
In reference to #449 and #447.

The search for Quran text currently works in mysterious way (ie. unclear). For example searching for `لل` doesn't include `الله` but will include `لله`.

I would like to improve this to be more intuitive as part of my academic project.

Areas to check:
- Search with regex (is this too much?)
- Search with/without diacritic
- Search scope option (like which translations)

I have not delved into the search code so I can't comment on the technical feasibility yet. Any advice is appreciated, especially on the UI aspect.

**Comment by ahmedre** [comment] 2015-03-07 18:37
these solutions are too much work to be worth doing imo due to the complexity of these solutions - i think that the best idea is to use the new quran.com search api when the device is connected.

@mmahalwy do you think alpha's quran search api is stable enough to include in quran android now or in the near future?

**Comment by ahmedre** [comment] 2015-03-07 18:41
see also #427 about some examples of poor search quality.

**Comment by mmahalwy** [comment] 2015-03-08 01:35
@ahmedre yeah its stable enough now. I think the improvement is the transliteration which I am waiting from you :)

**Comment by ahmedre** [comment] 2015-09-16 06:17
we should also search sura names.

**Comment by ahmedre** [comment] 2017-01-29 09:02
from email:
search for any word in basmallah returns the first ayah of most suras

**Comment by m7mdyahia** [comment] 2017-02-24 14:41
> another solution (just for documentation purposes) is bundling our own sqlite with the app with the unicode stemmer enabled (if it works, otherwise we may need our own Arabic stemmer) 

Unicode stemmer will not work in arabic as you expect it will not remove diacritic also it will not make equivlance between characters as (ي) and (ى) this is because unicode definittion for arabic language don't consider removing diacritic from text or matching similar letters as [normalization or canonical equivalence](https://en.wikipedia.org/wiki/Unicode_equivalence)

this could be tested using a newer version of sqlite on pc (I would appreciate if someone confirmed this)

so I think generally (for any arabic language search using fts sqlite)  for arabic language we need to write sqlite arabic tokinizer then see what could be done to ship it for android (I know this is alot of work but it will be very helpfull to many applications)

**Comment by sneetsher** [comment] 2018-05-29 06:59
Also  #268 quiet related. I agree with @ahmedre searching Arabic is vast topic and need to many underlying tools & libraries.

The best is to relay on another ready project that provide such feature for off-line search or if there no perfect solution some on-line API. Like the one mentioned quran.com.

I would suggest that you make a generic interface that allows you to switch search provider later for an off-line solution. 

@m7mdyahia There is new light Arabic stemmer. http://arabicstemmer.com/ by same main developer of Alfanous. Not if sure whether it helps.

Disclaimer: I am a user android app also contributor to Alfanous project (Unfortunately, it's Python based). Also its main developer Assem is my brother.

**Comment by ahmedre** [comment] 2018-12-28 18:37
> For example:how do i search فَاحْذَرُوهُ in verse 235 in surah baqarah. The hamza after ف has got a  ص at the top which is making the search not work.

**Comment by ahmedre** [comment] 2019-04-28 22:28
closing because fixed.

**Closed by ahmedre** 2019-04-28 22:28 UTC
