### ISSUE TITLE
Audio impossible to read Surat

### ISSUE THREAD

**Issue by Papisco** [quran/quran_android#903] opened 2017-07-16 11:33 UTC
As Salamou Aaleykoum,

It's impossible to listen some surat. Like Ta-Ha or Ya-Seen. 
I noticed that those are surats that doesn't start at the top of the page. The player keep playing the end of the previous surat which is at the beginning of the page.

NB: This issue is noticed on Quran Android app Amazon Kindle fire.

Best regards

**Comment by ozbek** [comment] 2017-07-17 07:33
Wa alaikum assalam.

To play from the start of a Sura, long press the first ayah and choose play from to context menu.

**Comment by Papisco** [comment] 2017-07-17 16:31
barakallahoufik, it's a bypass and it's working.
But I still think that's an issue that needs to be fixed.

**Comment by ozbek** [comment] 2017-07-17 19:37
That's by design... How would you rather want it to work?

**Comment by Papisco** [comment] 2017-07-17 19:48
If it's by design I understand.
I just thought that when a select a surah, The audio starts playing the selected one instead of the previous.
For instance I wanted to play Ta -Ha, I don't think that it should read the end of Maryam which is on the same page.

**Comment by ahmedre** [comment] 2020-03-27 18:08
this behavior changed now, so closing for now.

**Closed by ahmedre** 2020-03-27 18:08 UTC
