### ISSUE TITLE
[Turkish] Elmalili translation typos

### ISSUE THREAD

**Issue by Somaiagabr** [quran/quran_android#650] opened 2016-04-25 15:49 UTC
verse 8 and 9 of suratul Imraan.  This repetition caused irrelevance in all following verses.

**Comment by ozbek** [comment] 2016-08-24 05:27
It should be noted that the issue is only with Elmalili translation, the other one is OK.

**Comment by ozbek** [comment] 2017-01-29 12:19
Ugh! Elmalili translation has lots of spelling mistakes, too :(
E.g., `s` in place of `ş`, `I` instead of `İ`, `g` instead of `ğ`... impossibly many.

**Comment by ahmedre** [comment] 2017-01-29 21:14
@ozbek Can you find a better source for the data that we can switch to (I believe this one came from Tanzil)

**Comment by ozbek** [comment] 2017-01-30 04:21
Version in Tanzil has no issue in OP, also no spelling mistakes I mentioned.
I will ask around Turkish guys if there is an alternative source...

**Comment by ozbek** [comment] 2017-03-28 00:32
As mentioned above, the version in Tanzil does not have the issue in OP and the spelling mistakes. I also could not find any better (open) alternative to it. 

So, here is [quran.tr.db.zip](https://github.com/quran/quran_android/files/874155/quran.tr.db.zip) (please remove the .zip extension) - the dump from http://tanzil.net/trans/tr.yazir. I did not change the database version number.

**Comment by ozbek** [comment] 2017-05-08 06:31
Ping @ahmedre! :)

**Comment by ahmedre** [comment] 2018-11-30 18:58
`&quot` in 36:48

**Comment by ahmedre** [comment] 2018-11-30 18:59
@ozbek sorry for sitting so long on this - should i go ahead and push this?

**Comment by ahmedre** [comment] 2018-11-30 18:59
from an email:

> Arkadaşlar Ali İmran süresi 9 ayetinin meali yanlış olup tekrardan kontrol edip düzeltilmesi husunda yardımlarınızı rica ederim.

**Comment by ahmedre** [comment] 2018-11-30 19:50
from an email:

> I would like you to check on the Turkish translation of 3:10. It seems like it's shifted a bit.

**Comment by ahmedre** [comment] 2018-11-30 19:55
> 003:008

> Yukarıdaki ayetten sonra 
> Türkçe elmalılı meali kaymış.

**Comment by ahmedre** [comment] 2018-11-30 21:56
should your zip fix this problem also:

> Перевод с турецкого просто ужасен. Правила гармонии гласных не соблюдены. Вместо буквы ş поставили s, вместо буквы ğ поставили g. У меня один вопрос , вы что издеваетесь !!?? Я просто так целый час потратил в пустую !! ИСПРАВЬТЕ !!

jazakAllah khairan

**Comment by ozbek** [comment] 2018-11-30 23:01
> should your zip fix this problem also:
> 
> > Перевод с турецкого просто ужасен. Правила гармонии гласных не соблюдены. Вместо буквы ş поставили s, вместо буквы ğ поставили g. У меня один вопрос , вы что издеваетесь !!?? Я просто так целый час потратил в пустую !! ИСПРАВЬТЕ !!
> 
> jazakAllah khairan

Yes, that'd fix this issue.

**Comment by ahmedre** [comment] 2020-03-07 18:49
@ozbek really don't know how this fell off my radar for so long - just replaced Elmalılı Hamdi Yazır's database with the one you added. may you do a quick check on these (keep in mind some are in Diyanet Isleri translation like the very last one). really appreciate it, jazakAllah khairan.

**Comment by ozbek** [comment] 2020-03-09 04:37
JazakAllah khair, all above mentioned issues seem fixed.

Perhaps, this ticket can be closed (and please change the title to **[Turkish] Elmalili translation typos** as everything mentioned here is about that particular translation).

**Comment by ahmedre** [comment] 2020-03-09 07:52
waiyyakum, and jazakAllah khairan for looking into this - agreed and will re-title.

just wondering if [this comment](https://github.com/quran/quran_android/issues/650#issuecomment-443442546) is also fixed since it's about the Diyanet translation. jazakAllah khairan.

**Comment by ozbek** [comment] 2020-03-09 09:05
[As far as I can see](http://tanzil.net/#trans/tr.diyanet/3:199) there is no missing part in [that translation](https://github.com/quran/quran_android/issues/650#issuecomment-443442546) of Diyanet İşleri, it just seems an old version. Let's start a new thread about Diyanet İşleri translation as the one in the app is outdated.

**Comment by ahmedre** [comment] 2020-03-09 18:49
jazakAllah khairan! closing this one for now.

**Closed by ahmedre** 2020-03-09 18:49 UTC
Labels: Data
