### ISSUE TITLE
usage this project as library?

### ISSUE THREAD

**Issue by ahmadmust8** [quran/quran_android#836] opened 2017-03-28 01:43 UTC
can i use this project as part of my app via import it as library link or any other ways.
thanks a lot for the hard work you have done.

**Comment by ozbek** [comment] 2017-03-28 01:55
Possible duplicate of #695.

**Comment by ahmedre** [comment] 2017-04-20 08:40
not easily, no.
we're working on extracting portions as libraries - i have a working repo that handles downloads in a library so that it can be used in any app (not tied to Quran for Android). insha'Allah plan to do something similar with other parts of the app in the future.

but yeah, for now, you really can't, aside from either starting with it as your base app and modifying it or copying code.

**Closed by ahmedre** 2017-04-20 08:40 UTC
