### ISSUE TITLE
got error

### ISSUE THREAD

**Issue by tetouanweb** [quran/quran_android#872] opened 2017-05-15 11:32 UTC
Asalamo 3alaykom

i love ur app very much, and i have download it to get AJJR for you and for me by publishing it.

but when i have lunch android studio, i got this error : 

Error:Execution failed for task ':app:fabricGenerateResourcesMadaniBeta'.
> Crashlytics Developer Tools error.

**Comment by ozbek** [comment] 2017-05-15 23:09
Wa alaikum assalam.

Possible duplicate of #693.

**Closed** 2017-05-16 02:12 UTC
