### ISSUE TITLE
Quran playback speed adjustment

### ISSUE THREAD

**Issue by romaad** [quran/quran_android#899] opened 2017-06-22 01:18 UTC
Allow for adjuatment for the speed of the playback. I suggest using a scroll for increasing or decreasing playback speed.

**Comment by ozbek** [comment] 2017-06-22 01:35
Possible duplicate of #408.

**Comment by ahmedre** [comment] 2020-03-26 18:20
i get this request a lot but don’t really want to do this at this time. closing for now.

**Closed by ahmedre** 2020-03-26 18:20 UTC
